openapi: 3.0.0
info:
    title: Please Be Safe WEB TEAM API docs
    description: Please Be Safe WEB TEAM API 문서입니다
    version: 1.0.0
servers:
    - url: http://localhost:1234/
      description: Main (production) server
    - url: http://staging-api.example.com
      description: Internal staging server for testing
paths:
    /user:
        get:
            summary: Returns a list of users.
            description: Optional extended description in CommonMark or HTML.
            responses:
                '200': # status code
                    description: A JSON array of user names
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
    /user/login:
        post:
            summary: Creates a user.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    default: 'test123@test.com'
                                password:
                                    type: string
                                    default: '1234'
            responses:
                '201':
                    description: Created
